name: Daily Commit

on:
  schedule:
    - cron: '10 0 * * *'  # Runs every day at 00:10 UTC
  workflow_dispatch:       # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update timestamp 23f3002227@ds.study.iitm.ac.in
        run: |
          date >> daily.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily.txt
          git commit -m "Daily commit: $(date)"
          git push
