name: Daily Commit

on:
  schedule:
    - cron: '30 22 * * *'  # Every day at 22:30 UTC
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make a dummy commit - 23f3002227@ds.study.iitm.ac.in
        run: |
          echo "Updated at $(date -u)" > last-updated.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "23f3002227@ds.study.iitm.ac.in"
          git add last-updated.txt
          git commit -m "Automated commit on $(date -u)"
          git push
