name: Daily Commit

on:
  schedule:
    - cron: '30 22 * * *'  # Runs daily at 22:30 UTC
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make a dummy commit - 23f3002227@ds.study.iitm.ac.in
        run: |
          echo "Updated on $(date)" >> daily.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "23f3002227@ds.study.iitm.ac.in"
          git add daily.txt
          git commit -m "Automated daily commit"
          git push
