name: Daily Commit

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make empty commit - 23f3002227@ds.study.iitm.ac.in
        run: |
          git config user.name "GitHub Action"
          git config user.email "23f3002227@ds.study.iitm.ac.in"
          git commit --allow-empty -m "Daily commit $(date)"
          git push
