name: Daily Commit

on:
  schedule:
    - cron: '0 5 * * *'  # Daily at 5:00 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit change - 23f3002227@ds.study.iitm.ac.in
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "23f3002227@ds.study.iitm.ac.in"
          date > date.txt
          git add date.txt
          git commit -m "Daily commit"
          git push
